spring:
  datasource:
    url: postgres://trixowspfxgplx:9ec6db66e5822d193bcd2b9997d7a8232286aec390b11cd56baa385223f91b6b@ec2-52-4-104-184.compute-1.amazonaws.com:5432/df0adu5tj9absk
    username: trixowspfxgplx
    password: 9ec6db66e5822d193bcd2b9997d7a8232286aec390b11cd56baa385223f91b6b
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  messages:
    basename: base
  mail:
    default-encoding: UTF-8
    host: smtp.gmail.com
    username: mochamadnajib264@gmail.com
    password: ssmdogwjzqidgqrs
    port: 587
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
          connectiontimeout: 30000
          timeout: 30000
    protocol: smtp
    test-connection: false